# Generated by Django 2.0.3 on 2018-04-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_text_after',
            new_name='text_after',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_text_before',
            new_name='text_before',
        ),
    ]
