# Generated by Django 2.0.3 on 2018-04-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_person_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='review1',
        ),
    ]
