# Generated by Django 2.0.3 on 2018-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20180402_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review1',
            options={'verbose_name': 'Ревью', 'verbose_name_plural': 'Ревью'},
        ),
        migrations.AlterField(
            model_name='review1',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='review1',
            name='text_before',
            field=models.CharField(blank=True, help_text='полезная инфа', max_length=200, null=True, verbose_name='Текст до'),
        ),
    ]
