# Generated by Django 2.0.3 on 2018-04-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20180402_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Person'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_after',
            field=models.CharField(blank=True, help_text='Текст после авторедактирования', max_length=200, null=True, verbose_name='Текст после'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_before',
            field=models.CharField(blank=True, help_text='Текст до редактирования', max_length=200, null=True, verbose_name='Текст до'),
        ),
    ]
