# Generated by Django 2.0.3 on 2018-04-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20180403_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictCurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=15)),
            ],
        ),
    ]
