# Generated by Django 2.0.3 on 2018-04-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_dictexceptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictcurse',
            options={'verbose_name': 'Матерное слово', 'verbose_name_plural': 'Матерные слова'},
        ),
        migrations.AlterModelOptions(
            name='dictexceptions',
            options={'verbose_name': 'Не матерное слово', 'verbose_name_plural': 'Не матерные слова'},
        ),
    ]
